apiVersion: apps/v1
kind: Deployment
metadata:
  name: qyx-explorer
  labels:
    app: qyx-explorer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qyx-explorer
  template:
    metadata:
      labels:
        app: qyx-explorer
    spec:
      containers:
      - name: qyx-explorer
        image: qyx-explorer:latest
        ports:
        - containerPort: 80
        - containerPort: 50001
        env:
        - name: CANONICAL_URL
          value: "https://explorer.quantumyield.com"
        - name: SITE_TITLE
          value: "QYX Explorer"
        - name: API_URL
          value: "http://qyx-node:8332/"
        - name: NO_PRECACHE
          value: "0"
        - name: NO_ADDRESS_SEARCH
          value: "0"
        command:
        - bash
        - -c
        - "/srv/explorer/run.sh qyx-mainnet explorer"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi" 
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/blocks/tip/height
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/blocks/tip/height
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: qyx-data
          mountPath: /data
      volumes:
      - name: qyx-data
        persistentVolumeClaim:
          claimName: qyx-explorer-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: qyx-explorer-service
spec:
  selector:
    app: qyx-explorer
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: electrum
    port: 50001
    targetPort: 50001
  type: LoadBalancer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qyx-explorer-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qyx-explorer-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - explorer.quantumyield.com
    secretName: qyx-explorer-tls
  rules:
  - host: explorer.quantumyield.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qyx-explorer-service
            port:
              number: 80

---
# HorizontalPodAutoscaler for automatic scaling
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: qyx-explorer-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qyx-explorer
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80